const staffData = [
  {
    department: "EE",
    staff: [
      {
        name: "Pawan Kumar",
        designation: "Senior Technical Assistant",
        experience: "10 Years",
        education: "B.E. Electrical Engineering",
        expertise: "Power System Lab",
        email: "pk.elec@nitp.ac.in",
        mobile: "7488272194",
        image: "https://i.postimg.cc/BbWvt0tC/image.png",
      },
      {
        name: "Pintu Kumar",
        designation: "Senior Technical Assistant",
        experience: "10 Years",
        education: "Diploma & B.E. (Electrical Engineering), BA & PG (Political Science)",
        expertise: "Control System Lab",
        email: "pintu.ee@nitp.ac.in",
        mobile: "6200749596",
        image: "https://i.postimg.cc/fRgDJNr0/image.png",
      },
      {
        name: "Pushkar",
        designation: "Technical Assistant (On Contract)",
        experience: "11 Years",
        education: "M.Sc.",
        expertise: "Elements of Electrical Engineering, Electrical Machine Lab",
        email: "Pushkar24feb89@gmail.com",
        mobile: "9708902402",
        image: "https://i.postimg.cc/vmR2P21N/image.png",
      },
      {
        name: "Ratikanta Behera",
        designation: "Technical Assistant",
        experience: "10 Years",
        education: "Diploma (Electrical Engineering), BA & PG (Political Science)",
        expertise: "Basic Electrical and Electrical Machine Lab, IDC Lab",
        email: "r.behera_ee@nitp.ac.in",
        mobile: "7970670572",
        image: "https://i.postimg.cc/RZwL0SFg/image.png",
      },
      {
        name: "Abhishek Kumar Sah",
        designation: "Technical Assistant",
        experience: "10 Years",
        education: "Diploma in Electrical Engineering",
        expertise: "",
        email: "a.k.sah_ee@nitp.ac.in",
        mobile: "7894792534",
        image: "https://i.postimg.cc/nzh4Tq1W/image.png",
      },
      {
        name: "Ashish Kumar Baranwal",
        designation: "Technical Assistant",
        experience: "10 Years",
        education: "Diploma & B.Tech (Electrical Engineering), BA & PG (Political Science)",
        expertise: "Basic Electrical and Electrical Machine Lab, Microprocessor and Microcontroller Lab",
        email: "ashish.k_ee@nitp.ac.in",
        mobile: "8190955567",
        image: "https://i.postimg.cc/FzfjXm8g/image.png",
      },
      {
        name: "Amresh Kumar",
        designation: "Technical Assistant",
        experience: "4 Years",
        education: "Diploma in Electrical Engineering, CITS",
        expertise: "Basic Electrical and Electrical Machine Lab",
        email: "amresh.ta@nitp.ac.in",
        mobile: "7870744027",
        image: "https://i.postimg.cc/g2b3QCD8/image.png",
      },
      {
        name: "Akash Lal",
        designation: "Technical Assistant",
        experience: "22 Months",
        education: "M.Tech (Power System)",
        expertise: "Power System",
        email: "Akash.ta@nitp.ac.in",
        mobile: "7717703407",
        image: "https://i.postimg.cc/pTrjKRWb/image.png",
      },
      {
        name: "Navin Kumar",
        designation: "Technical Assistant",
        experience: "3 Years",
        education: "B.Tech",
        expertise: "Electrical Machine",
        email: "Navin.ta@nitp.ac.in",
        mobile: "8709084390",
        image: "https://i.postimg.cc/C1941zj6/image.png",
      },
      {
        name: "Manda Sathish",
        designation: "Technical Assistant",
        experience: "8 Years",
        education: "M.Tech (Power Electronics)",
        expertise: "Power Electronics",
        email: "sathish.ta@nitp.ac.in",
        mobile: "8985424063",
        image: "https://i.postimg.cc/tCQ5GnRs/image.png",
      },
      {
        name: "Umesh Prasad",
        designation: "Office Attendant (SG-II)",
        experience: "33 Years",
        education: "Matric",
        expertise: "Office",
        email: "",
        mobile: "7677205648",
        image: "https://i.postimg.cc/PqxbQmyR/image.png",
      },
      {
        name: "Ashok Kumar",
        designation: "Office Attendant (SG-II)",
        experience: "33 Years",
        education: "8th",
        expertise: "Office",
        email: "Kashok.adm@gmail.com",
        mobile: "7463094488",
        image: "https://i.postimg.cc/PxvmBTBb/image.png",
      },
      {
        name: "Aditya Kumar",
        designation: "Lab Assistant",
        experience: "11 Years",
        education: "ITI (Electrician), Graduation",
        expertise: "Basic Electrical Engineering",
        email: "Kumaradityanitp@gmail.com",
        mobile: "8051729359",
        image: "https://i.postimg.cc/T1qW6wQb/image.png",
      },
      {
        name: "Rajesh Goswami",
        designation: "Computer Operator",
        experience: "11 Years 9 Months",
        education: "ITI",
        expertise: "Computer Operation (Data Entry, Administrative Support)",
        email: "goswamirajesh68@gmail.com",
        mobile: "8210205225",
        image: "https://i.postimg.cc/yxPWGGYX/image.png",
      },
    ],
  },
];

export default staffData;
