const staffData = [
  {
    department: "Civil",
    staff: [
      {
        name: "Dr. Abidhan Bardhan",
        designation: "Sr. Technical Assistant",
        experience: "Geotechnical Engineering",
        education: "Ph.D",
        expertise: "Geotechnical Engineering",
        email: "abidhan@nitp.ac.in",
        mobile: "+91-9088265565",
        image: "https://i.postimg.cc/VLRjCKWF/image.png",
      },
     
      {
        name: "Mr. Lal Babu Tiwari",
        designation: "Sr. Technical Assistant",
        experience: "9 Years 5 Months",
        education: "B.Tech",
        expertise: "Civil Engineering",
        email: "lalbabut.ce@nitp.ac.in",
        mobile: "+91-6205207798",
        image: "https://i.postimg.cc/NfqcH4jL/image.png",
      },
      {
        name: "Mr. Gautam Kumar",
        designation: "Sr. Technical Assistant",
        experience: "9 Years 5 Months 15 Days",
        education: "PhD and M.Tech",
        expertise: "Structural Engineering",
        email: "Gautamkr.ce@nitp.ac.in",
        mobile: "+91-8507015142",
        image: "https://i.postimg.cc/Gp9NN8mZ/image.png",
      },
      {
        name: "Mr. Rajesh Ranjan",
        designation: "Technical Assistant",
        experience: "10th Jan 2017 to Present – Technical Assistant (Civil Engineering Department) NIT Patna",
        education: "B.Tech ",
        expertise: "Civil Engineering",
        email: "rajeshr.ce@nitp.ac.in",
        mobile: "+91-8709831540",
        image: "https://i.postimg.cc/TP7x5vKX/image.png",
      },
      {
        name: "Mr. Ankit Anand",
        designation: "Technical Assistant",
        experience: "1 Year 2 Months 19 Days",
        education: "B.Tech.",
        expertise: "Civil Engineering",
        email: "Ankit.ta@nitp.ac.in",
        mobile: "+91-9576767822",
        image: "https://i.postimg.cc/N01TQbFT/image.png",
      },
      {
        name: "Mr. Gaurav Kushwaha",
        designation: "Technician",
        experience: "5 Months",
        education: "Diploma",
        expertise: "Environmental Engineering",
        email: "gaurav.tech@nitp.ac.in",
        mobile: "+91-8303143094",
        image: "https://i.postimg.cc/7ZhmYvrz/image.png",
      },
    ],
  },
];

export default staffData;
